### PR TITLE
Milestone 6: friendship v2

### PR DESCRIPTION
**Pull request by CornerstoneII**
This is a pull request for the project Social media website frienships-v2 where we created a model with associations and all requested features for friendships and the respective tests.

### CODE REVIEW

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
## Hello @Igors78 !!! 🚀 

Good job on the previous milestone, but the requirements for this project were not implemented yet.

# Changes Requested :recycle:

The Basic feature that should be added to your project in this milestone is:

- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created.
**Hint:** You can use the method that changes the status of the friendship to create a new friendship using the users in reverse roles. (The user will be the friend and the friend will be the user). 

That change will allow you to optimize your database queries.

- [x]  Right now you are using **active_friends** for two different associations, so the query of your timeline posts is not presenting the right behavior. I mean, the posts are not been displayed for both sides of the friendship. Please fix the behavior and optimize the query. **HINT** With the implementation of a new reverse row, you will not need two different sources, you can just query the current_user.friends because for each confirmed friendship we will have a row with that user in the user role and in the friend role.
- [ ] Add unit and integration tests to confirm the new feature behavior.

**Important**

- [ ] Edit your pull request message to have a brief summary about the changes done in that milestone. And for the next project, please make sure to use the right workflow creating separated branches for each milestone, committing your changes in the right branch, and submitting the same pull request for all the reviews of the same milestone.

# To Hightlight 🌟 
 - You have done a great job using associations to query the requested and pending friendships. 

Keep going with the hard work! 💪🏻 
Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc_.**

**Review by mke2111 — CHANGES_REQUESTED** [review]
Under Review, Please hold on.

**Review by enaburekhan — APPROVED** [review]
# Status: Approved:heavy_check_mark:
**Hi Iyadi!
Congratulations on this milestone:clap::clap:. All the tests passed and cover both positive and negative case scenarios:100:.** 
**Move on with the next milestone:walking:. And don't forget to merge the PR and fill the project completion form.**

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Review by oloomoses — COMMENTED** [review]
# Project name: Social media website - Milestone: deploy - Changes Required :recycle: 
**Hello team, the live link provided is not working. Kindly ensure that the app is deployed on Heroku and provide the correct link in the readme file**

Kindly implement the above changes before submitting another review.

**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply**

_Slack: Oloo Moses_

**Review by NtwaliHeritier — COMMENTED** [review]
### **STATUS: Changes requested🛑🛑🛑🛑**

Hello team,
Great work on this project. It's about to end🙌.

However a small change is required.

[REQUIRED]: It looks like you already merged your branches and I am unable to review this PR. Kindly revert and ask for another review.

Make the requested changes and ask for another review
Happy coding💻💻💻

**Pull request merged**
